# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---


### Exercise 1:
Create a NumPy array of integers from 1 to 10.

# Exercise 1

In [4]:
import numpy as np

In [5]:
I = np.arange(1,11)
print(I)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [7]:
A = np.zeros((3,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [9]:
W = np.linspace(0, 5, 10)
print(W)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [11]:
M = np.eye(5)         
print(M)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [13]:
e = np.random.random((4,4)) 
print("E=",e)   

E= [[0.94752295 0.93323028 0.46070664 0.70195984]
 [0.38648258 0.01470888 0.01874509 0.17235362]
 [0.63391798 0.36337605 0.01099445 0.05218082]
 [0.42585284 0.99056121 0.72612567 0.16206534]]


### Exercise 6:
Find the shape of a NumPy array.

In [15]:
t = np.array([[5,10,40],[7,0,3]])    
print(t.shape)                     
print(t[1, 0], t[1, 1], t[1, 2]) 

(2, 3)
7 0 3


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [17]:
o = np.arange(1,17).reshape((4,4))         
print(o)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### Exercise 8:
Find the data type of the elements in a NumPy array.

In [19]:
dt= np.array([3, 0, 7])
print(dt.dtype)

int32


### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [21]:
r = np.arange(1,101)
r[(r%2 == 0)]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [23]:
f = np.random.randint(10,51, size=(6, 6))
print(f)

[[28 13 37 33 22 14]
 [39 18 22 34 28 18]
 [31 26 13 14 17 47]
 [37 42 39 13 25 45]
 [21 13 12 25 43 32]
 [29 21 30 48 27 30]]


In [24]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)

    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [26]:
a = np.array([[1,2,3,4], [5,6,7,8]])
b = a[:2, 1:2]
print(b)

[[2]
 [6]]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [28]:
x = np.array([1,3,4,6,7])
print(np.sum(x))

21


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [30]:
x = np.array([1,3,4,6,7])
print(np.mean(x))

4.2


In [31]:
x = np.array([1,3,4,6,7])
print(np.median(x))

4.0


In [32]:
x = np.array([1,3,4,6,7])
print(np.std(x))

2.1354156504062622


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [34]:
g = np.random.randint(1,7,(3,3))
c = np.max(g, axis=1)
h = np.min(g, axis=1)
print(g)
print(c)
print(h)

[[5 5 3]
 [2 5 4]
 [6 2 4]]
[5 5 6]
[3 2 2]


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [36]:
v = np.random.randint(1,50,20)
h = np.max(v)
k = np.min(v)
p = np.argmax(v)
o = np.argmin(v)
print(v)
print(h)
print(k)
print(p)
print(o)

[ 9 27 49 11 41  9 34 26 14 18 22 29 31 24  9 34 34  5 11 23]
49
5
2
17


### Exercise 16:
Create a NumPy array and reverse its elements.

In [38]:
g = np.array([1,7,9,8])
print(g[::-1])

[8 9 7 1]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [40]:
z = np.random.randint(1,7,(3,3))
f = np.random.randint(2,4,(3,3))
print(z)
print(f)

[[1 4 3]
 [5 3 5]
 [2 1 6]]
[[3 2 3]
 [3 2 2]
 [3 3 3]]


In [41]:
d = np.multiply(z,f)
print(d)

[[ 3  8  9]
 [15  6 10]
 [ 6  3 18]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

In [43]:
d = np.array([12, 4, 2, 1])
f = np.diagflat(d)
print(f)

[[12  0  0  0]
 [ 0  4  0  0]
 [ 0  0  2  0]
 [ 0  0  0  1]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [45]:
z = np.random.randint(1,7,(3,3))
f = np.random.randint(2,4,(3,3))
print(z)
print(f)

[[2 1 5]
 [6 1 3]
 [4 6 6]]
[[2 2 2]
 [3 3 2]
 [3 3 2]]


In [165]:
d = np.dot(z,f)
print(d)

[[22 22 16]
 [24 24 20]
 [44 44 32]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [48]:
y=np.arange(2,6).reshape((2,2))
y.flatten()

array([2, 3, 4, 5])

### Exercise 21:
Stack two NumPy arrays vertically.

In [50]:
s = np.array([1,2,3,4])
d = np.array([5,6,7,8])
np.vstack((s,d))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Exercise 22:
Stack two NumPy arrays horizontally.

In [52]:
s = np.array([1,2,3,4])
d = np.array([5,6,7,8])
np.hstack((s,d))

array([1, 2, 3, 4, 5, 6, 7, 8])

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [85]:
x = np.array([9, 11, 12, 13, 14,15])
y = np.split(x, [2, 4])
print(x)
print(y)

[ 9 11 12 13 14 15]
[array([ 9, 11]), array([12, 13]), array([14, 15])]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [90]:
a = np.random.rand(1, 2)
b = np.round(a, 2)
print (a)
print(b)

[[0.94780456 0.46443903]]
[[0.95 0.46]]


### Exercise 25:
Find the unique elements of a NumPy array.

In [104]:
w = np.array([6, 7, 8, 9, 10, 11, 12])
v = np.unique(w)
print(v)

[ 6  7  8  9 10 11 12]


### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [109]:
b = np.array([1, 5, 3, 8, 2, 7])
value = 4
b[b < value] = value
print(b)

[4 5 4 8 4 7]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [118]:
u = np.array([7, 6, 9])
cum= np.cumsum(u)
print(cum)

[ 7 13 22]


### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [134]:
g = np.array([0, 1, 2, 0, 3, 4, 0, 5])
not_zero = np.count_nonzero(g)
print(not_zero)

5


### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [136]:
t = np.random.randint(1, 51, size=7)
c = np.sort(t)
print(t)
print(c)

[29  9 21 10 18 34  3]
[ 3  9 10 18 21 29 34]


### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [157]:
a = np.array([[1,2,3], [5,6,7],[8,9,10]])
s = np.sum(a, axis=1)
c = np.sum(a, axis=0)
print(a)
print(s)
print(c)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
[ 6 18 27]
[14 17 20]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

In [162]:
e = np.random.rand(2, 3)
min = np.min(e)
max = np.max(e)
norm = (e - min) / (max - min)
print(e)
print(norm)

[[0.71813564 0.23224726 0.01218684]
 [0.53544361 0.24728902 0.02188397]]
[[1.         0.31172292 0.        ]
 [0.74121065 0.33303007 0.0137363 ]]


### Exercise 32:
Create two NumPy arrays and find the dot product.

In [167]:
a = np.array([[1,2,3], [5,6,7],[8,9,10]])
b = np.array([[4,5,6], [9,5,3],[4,6,10]])
x = np.dot(a,b)
print(x)

[[ 34  33  42]
 [102  97 118]
 [153 145 175]]


### Exercise 33:
Find the trace of a square NumPy matrix.

In [172]:
m = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
tr = np.trace(m)
print(m)
print(tr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


### Exercise 34:
Create a 2D array and swap two rows.

In [179]:
s = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
x = s[[0, 1]] = s[[1, 0]] # Swap the first row (index 0) and the second row (index 1)
print(s)
print(x)



[[4 5 6]
 [1 2 3]
 [7 8 9]]
[[4 5 6]
 [1 2 3]]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

In [184]:
d = np.array([1, 2, 3, 4, 5])
col_vec = d.reshape(-1, 1)
print("Original 1D array:")
print(d)
print("\nColumn vector:")
print(col_vec)

Original 1D array:
[1 2 3 4 5]

Column vector:
[[1]
 [2]
 [3]
 [4]
 [5]]


### Exercise 36:
Find the determinant of a 3x3 matrix.

In [189]:
m = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
d = np.linalg.det(m)
print(m)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6.66133814775094e-16


### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [194]:
x = np.array([[4, 2], [1, 3]])
eigenval, eigenvec = np.linalg.eig(x)
print(x)
print(eigenval)
print(eigenvec)

[[4 2]
 [1 3]]
[5. 2.]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


### Exercise 38:
Solve a system of linear equations using NumPy.

In [199]:
A = np.array([[2, 3],[4, 1]])
b = np.array([8, 9])
sol = np.linalg.solve(A, b)
print(sol)

[1.9 1.4]


### Exercise 39:
Add Gaussian noise to a NumPy array.

In [204]:
P = np.array([1, 2, 3, 4, 5])
# Here for specify the mean and standard deviation of the Gaussian noise
mean = 0
std_dev = 0.5
# Gaussian noise
y = np.random.normal(mean, std_dev, P.shape)
# By adding a noise
d = P + y
print("P: is Original array:", P)
print("Y: Gaussian noise:", y)
print("d :Noisy array:", d)


P: is Original array: [1 2 3 4 5]
Y: Gaussian noise: [ 0.18470801 -0.25835569 -0.49191891 -0.17175036 -0.31186978]
d :Noisy array: [1.18470801 1.74164431 2.50808109 3.82824964 4.68813022]


### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

In [209]:
m = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12],[13, 14, 15, 16]])
diag = np.diagonal(m)
print(m)
print(diag)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]
